# Generated by Django 4.1.7 on 2023-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news/')),
                ('created', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Подкаст',
                'verbose_name_plural': 'Подкасты',
            },
        ),
    ]
