# Generated by Django 4.1.7 on 2023-03-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_podcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='title',
            new_name='category',
        ),
    ]
