# Generated by Django 4.1.7 on 2023-03-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_rename_title_podcast_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='addvert/')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
    ]
