# Generated by Django 4.1.7 on 2023-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_addvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvert',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
